name: "Bug Report"
description: "File a bug report"
title: "XXXXX [2023/XX/XX]"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please enter an explicit description of your issue"
      placeholder: "Short and explicit description of your incident..."
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - 1 - Critical
        - 2 - High
        - 3 - Medium
        - 4 - Low
        - 5 - None
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "The version the software was written in."
  - type: textarea
    id: system
    attributes:
      label: "System informations"
      description: "What are some details about your software?"
      value: |
        Platform: Windows/Mac
        Mono version: X.X.X
  - type: textarea
    id: inputs
    attributes:
      label: "Steps taken"
      description: "What did you do to arrive at this point?"
  - type: textarea
    id: expected
    attributes:
      label: "Expected result"
      description: "What were you expecting to happen?"
  - type: textarea
    id: workaround
    attributes:
      label: "Workaround or solution"
      description: "If you found a workaround or know how to fix the issue, please share it here."
  - type: textarea
    id: other
    attributes:
      label: "Other"
      description: "If you have anything else to say"
  - type: markdown
    attributes:
      value: "Please attach any input, output or log file that could help with this issue."
